### ISSUE TITLE
Crash when checking decayable property

### ISSUE THREAD

**Issue by ZephaniahNoah** [cleverpanda/BirdsNests#12]
The leaves from the Dynamic Trees mod crash the game when you break them. I reported this to the dev and he said it's a problem with Birds Nests trying to get a decayable property from the leaves.
He suggested possible fix [here](https://github.com/ferreusveritas/Dynamic-Trees/issues/11#issuecomment-338477889).
MC: 1.11.2

**Comment by cleverpanda** [comment]
fixed 2.1.0+
