### ISSUE TITLE
Include full source tree

### ISSUE THREAD

**Issue by josephcsible** [cleverpanda/BirdsNests#13]
A few important files are missing from this repository:
- gradle/
- .gitignore
- build.gradle
- gradle.properties
- gradlew
- gradlew.bat

Can you add these? (build.gradle is really the most important, since the rest can be assumed to be pretty much verbatim from the MDK.)

**Comment by cleverpanda** [comment]
Whoops. Yes.

**Comment by cleverpanda** [comment]
It's there. Thanks for your patience
