### ISSUE TITLE
Minor Issue: Misnamed in MultiMC Instance

### ISSUE THREAD

**Issue by XvBUSHvX** [cleverpanda/BirdsNests#14]
This is probably a null issue. I use MultiMC for working with mod packs and noticed on the list the BirdsNests1.12.2-2.0.0.jar shows up as "Corn Crop Mod" under an instances' mod list. Unfortunately I don't know what MMC uses to determine what name is used for the list.

I did check in the launched instance however and the mod is listed correctly under the mods options and under JEI's item search so there are likely very few others that will notice this behavior.

**Comment by cleverpanda** [comment]
The file it uses is called mcmod.info.
Fixed 2.1.0+
