### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [cleverpanda/BirdsNests#15]
[crash-2017-12-28_14.00.58-server.txt](https://github.com/cleverpanda/BirdsNests/files/1591070/crash-2017-12-28_14.00.58-server.txt)
hope the report tells everything

**Comment by ghost** [comment]
and also, can you update your forge to 2555 please? on 1.12.2. thanks

**Comment by cleverpanda** [comment]
Fixed and done. 2.1.0+
