### ISSUE TITLE
Issue with EZ Storage and Birds Nests

### ISSUE THREAD

**Issue by DatrixTHLK** [cleverpanda/BirdsNests#3]
Hi CleverPanda,

I would like to keep you updated with this issue I seem to be having.
https://github.com/zerofall/EZStorage2/issues/42

**Comment by DatrixTHLK** [comment]
Here is also another issue that may help give more information. I'm trying to figure this out. 

https://github.com/Malorolam/LootBags/issues/33

What is basically happening, when I first start up minecraft my loot bags/birds nest let me have the items from them, but once I go into the EZ Storage 2 Inventory Storage Box, the items that are in the characters inventory get shuffled around. Malorolam said it is a possiblitiy that a de-syncing is occurring between client and server. 

After shuffling the characters inventory around I go out of the gui with the birds nests in the main hand slots and proceed to right click them no items pop out of them but the item goes right back to my characters inner inventory slots. Right after that, hitting E shows the characters inventory and the items have been reshuffled back to where they originally were before I moved them around in the EZStorage 2 Inventory storage box. 

**EDIT:** I will do a bit of digging myself seeing as how I've done this countless times before. It might be something else entirely. I will get back to you a bit later when I've found out what the issue is or what it might be. I will be updating you on the progress as it happens.

**EDIT 2:** LightningCraft 2.6.0 and the recent version of Forge (2111) was having an issue and the mod author of LC has been made aware of the issue

**Comment by DatrixTHLK** [comment]
I will do a bit of digging myself seeing as how I've done this countless times before. It might be something else entirely. I will get back to you a bit later when I've found out what the issue is or what it might be. I will be updating you on the progress as it happens.

**Comment by cleverpanda** [comment]
Okay then.

**Comment by DatrixTHLK** [comment]
Well so far it isn't reproducable anymore so the issue fixed itself.
