### ISSUE TITLE
NEST_DROP_RARITY doesn't work?

### ISSUE THREAD

**Issue by ghost** [cleverpanda/BirdsNests#5]
Birds Nests Version: 1.4
Forge Version: 1.10.2-12.18.2.2120

I'm confused about how the NEST_DROP_RARITY config option works. I'm assuming it's a 1/X value. I want that nests drops are really rare, so I set it from 24 (standard) to 50. Then I started a new game, cut one big tree and got about 20+ nests. I think this is too much for a 2% drop chance. Can you please clarify what's happening?

Addition: It was a tree generated by Biomes O' Plenty, but the leaves were normal oak leaves. I also use WTF's Expedition's feature for dropping sticks from leaves. Maybe some sort of incompatibility issue?

Addition 2: After opening a lot of nests in creative mode, I ended with way too much good stuff for that amount of nests. I set all values a lot higher, e.g. emerald and diamond to 1000, and that gave me adequate results in my opinion. Maybe you want to take a second look at your random number generator.

**Comment by cleverpanda** [comment]
Investigating it.

**Comment by ghost** [comment]
I started another new world on my server and there the drop rarity from leaves seems to be how I expect it to be (with my setting of 50). I also fine tuned the drops list, added some mod items etc. - want to say I'm fine with how it is now, but maybe you still want to investigate and find something.

Nice mod btw, my girlfriend loves to collect the nests. ;-)
