### ISSUE TITLE
Bird's Nest item is gone in most recent build (32x)

### ISSUE THREAD

**Issue by WesCook** [cleverpanda/BirdsNests#8]
In the latest build (BirdsNests_32x.zip), the Bird's Nest item seems to be missing from the game completely.  It doesn't drop from trees, nor show in JEI.

There's no changelog to suggest what has changed.

**Comment by cleverpanda** [comment]
That's because it's a texture pack. 
I'll specify on the page

**Comment by WesCook** [comment]
Hi panda,

I see, that makes sense.  The problem is though that now any auto-downloaders (such as the Curse client) will only download the texture pack, and overwrite the .jar.  That's why I was seeing the item deleted from the game.

Instead of uploading it as a release, I'd suggest including it as a download link on the main page.  Or push a new update after the texture pack so at least it's not the "latest release version".

**Comment by cleverpanda** [comment]
Ah I see. I'll archive that on and add it as an additional attachment instead, thanks
